name: pokedex
description: An Application to view the pokemon of the PokeApi.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.9
  flex_color_scheme: ^5.1.0
  freezed_annotation: ^2.1.0
  go_router: ^4.2.8
  dartz: ^0.10.1
  dio: ^4.0.6
  json_annotation: ^4.6.0
  dartx: ^1.1.0
  cached_network_image: ^3.2.1
  transparent_image: ^2.0.0
  flutter_svg: ^1.1.4
  collection: ^1.16.0
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0
  json_serializable: ^6.3.1
  widgetbook_generator: ^2.4.1
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/types/
